source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'bibtex-ruby', '>= 5.1.0'
    # gem 'kramdown', '>= 2.3.0'
    # gem 'yajl-ruby', '>= 1.3.1'
    # gem 'RedCloth', '>= 4.3.0'
end
